# Generated by Django 4.0.3 on 2022-05-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_students_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
