# Generated by Django 4.0.3 on 2022-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_employees_employee_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
