# Generated by Django 4.0.3 on 2022-06-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
