# Generated by Django 4.0.3 on 2022-06-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='ali', max_length=255),
            preserve_default=False,
        ),
    ]
