# Generated by Django 4.0.3 on 2022-06-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_employee_logedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='Username',
            field=models.CharField(default='ali', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
