# Generated by Django 4.0.3 on 2022-07-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_employee_name_employee_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='female',
            field=models.BooleanField(default=False),
        ),
    ]
