# Generated by Django 4.0.3 on 2022-07-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mail',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
