# Generated by Django 4.0.3 on 2022-07-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_employee_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
